#include <archive.h>
#include <archive_entry.h>
#include <stdlib.h>
#include <string.h>

#define GET_VAR(NAME) long get_ ## NAME (){return NAME;}
GET_VAR(ARCHIVE_VERSION_NUMBER)
GET_VAR(ARCHIVE_EOF)
GET_VAR(ARCHIVE_OK)
GET_VAR(ARCHIVE_RETRY)
GET_VAR(ARCHIVE_WARN)
GET_VAR(ARCHIVE_FAILED)
GET_VAR(ARCHIVE_FATAL)
GET_VAR(ARCHIVE_EXTRACT_OWNER)
GET_VAR(ARCHIVE_EXTRACT_PERM)
GET_VAR(ARCHIVE_EXTRACT_TIME)
GET_VAR(ARCHIVE_EXTRACT_NO_OVERWRITE)
GET_VAR(ARCHIVE_EXTRACT_UNLINK)
GET_VAR(ARCHIVE_EXTRACT_ACL)
GET_VAR(ARCHIVE_EXTRACT_FFLAGS)
GET_VAR(ARCHIVE_EXTRACT_XATTR)
GET_VAR(ARCHIVE_EXTRACT_SECURE_SYMLINKS)
GET_VAR(ARCHIVE_EXTRACT_SECURE_NODOTDOT)
GET_VAR(ARCHIVE_EXTRACT_NO_AUTODIR)
GET_VAR(ARCHIVE_EXTRACT_NO_OVERWRITE_NEWER)
GET_VAR(ARCHIVE_EXTRACT_SPARSE)
GET_VAR(ARCHIVE_EXTRACT_MAC_METADATA)
GET_VAR(ARCHIVE_EXTRACT_NO_HFS_COMPRESSION)
GET_VAR(ARCHIVE_EXTRACT_HFS_COMPRESSION_FORCED)
GET_VAR(ARCHIVE_EXTRACT_SECURE_NOABSOLUTEPATHS)
GET_VAR(ARCHIVE_EXTRACT_CLEAR_NOCHANGE_FFLAGS)
GET_VAR(ARCHIVE_EXTRACT_SAFE_WRITES)

#define GET_SVAR(NAME) char* get_ ## NAME (){return NAME;}
GET_SVAR(ARCHIVE_VERSION_ONLY_STRING)
GET_SVAR(ARCHIVE_VERSION_STRING)

/* TODO: all other defines from archive.h */
